#!/bin/bash

set -o errexit -o nounset -o pipefail

if rc="$HOME/.cmdsuggestrc"; [[ ! -f "$rc" || ! -r "$rc" ]]; then
	printf 'bad %s\n' "$rc"
	exit 1
fi

. ~/.cmdsuggestrc

temp="$(mktemp)"
trap 'rm -- "$temp"' EXIT

cat >"$temp"
run_cmdsuggest "$temp"
