#!/bin/bash

opts=() args=()

for arg in "$@"; do
	if [[ "$arg" == '--' ]]; then
		for arg in "$@"; do
			args+=("$arg")
			shift
		done
		break
	elif [[ "$arg" =~ ^- ]]; then
		opts+=("$arg")
		shift
	else
		args+=("$arg")
		shift
	fi
done

systemctl -o json "${opts[@]}" list-units "${args[@]}" | jq --raw-output '.[].unit'
