#!/bin/bash

OTPS=() ARGS=()

for arg in "$@"; do
	if [[ "$arg" == '--' ]]; then
		for arg in "$@"; do
			ARGS+=("$arg")
			shift
		done
		break
	elif [[ "$arg" =~ ^- ]]; then
		OPTS+=("$arg")
		shift
	else
		ARGS+=("$arg")
		shift
	fi
done

systemctl -o json "${OPTS[@]}" list-units "${ARGS[@]}" | jq --raw-output '.[].unit'
